---
title: "Household Income from the 5-Year ACS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Household Income from the 5-Year ACS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rlang)
library(magrittr)
library(hiRx)

DATA_PATH <- file.path(path.expand("~"),
                       "Higher Expectations/Data")

SHAPEFILE_PATH <- file.path(DATA_PATH,
                            "Downloads/Census Shapefiles")
```

## American Community Survey 5-Year Tables

### Median Household Income

```{r decennial_income_settings}
.ACS5_INCOME_VARIABLES <- tibble::tribble(
    ~ Variable, ~ "Race/Ethnicity",
    "B19013_001E", "Everybody",
    "B19013H_001E", "White",
    "B19013B_001E", "Black",
    "B19013I_001E", "Latin@"
)

.ACS5_INCOME_YEARS <- seq(2010, 2020, by = 5) %>% purrr::set_names()

CPI <- readr::read_csv(
    file.path(DATA_PATH,
              "Downloads",
              "us annual consumer price index.csv"),
    col_types = readr::cols(Year = readr::col_integer(),
                            Annual = readr::col_double())
    )

.ACS5_INCOME_SETTINGS <- tibble::tibble(Year = .ACS5_INCOME_YEARS) %>%
    dplyr::left_join(CPI, by = "Year") %>%
    dplyr::arrange(.data$Year) %>%
    dplyr::mutate(Ratio = dplyr::last(.data$Annual) / .data$Annual)

```

```{r load_blocks}
BLOCK_FILES <- c(
    `2000` = "tl_2010_55101_tabblock00.shp",
    `2010` = "tl_2010_55101_tabblock10.shp",
    `2020` = "tl_2020_55_tabblock20.shp"
)

BLOCKS <- hiRx::census_tigershapes_combine(BLOCK_FILES,
                                           SHAPEFILE_PATH,
                                           .data$COUNTYFP == "101") %>%
    dplyr::filter(.data$INTPTLON < -87.7,
                  .data$INTPTLON > -87.96)
```

```{r acquire_incomes}
RAW_INCOMES <- .ACS5_INCOME_YEARS %>%
    purrr::map(
        function(n, ...) acs5_query_url(year = n, ...),
        variables = paste0(.ACS5_INCOME_VARIABLES$Variable,
                           collapse = ","),
        for_geo = "tract",
        for_items = paste0(unique(BLOCKS$TRACTCE),
                           collapse = ","),
        state = 55,
        county = 101
    ) %>%
    purrr::map(
        hiRx::census_do_api_query
    )
```

```{r wrangle_incomes}
INCOME_BY_TRACT <- RAW_INCOMES %>%
    purrr::map(
        hiRx::census_json_to_tibble,
        variable_names = .ACS5_INCOME_VARIABLES$Variable,
        .val_trans_f = ~ readr::parse_integer(., na = c("", "NA", "NULL", "-666666666")),
        .value_column = "Income"
    ) %>%
    dplyr::bind_rows(
        .id = "Year"
    ) %>%
    dplyr::mutate(
        Year = as.integer(.data$Year),
        Vintage = 10 * floor(0.1 * .data$Year)
    ) %>%
    dplyr::left_join(
        .ACS5_INCOME_VARIABLES,
        by = "Variable"
    ) %>%
    dplyr::select(
        !.data$Variable
    ) %>%
    dplyr::left_join(
        .ACS5_INCOME_SETTINGS,
        by = "Year"
    ) %>%
    dplyr::mutate(
        `Income in 2020 Dollars` = .data$Income * .data$Ratio
    ) %>%
    dplyr::select(
        !c(.data$Annual, .data$Ratio)
    )
```

### Median Incomes by Race and Location

```{r wrangle_income_locations}
INCOME_BY_MUNI <- INCOME_BY_TRACT %>%
    dplyr::inner_join(
        dplyr::bind_rows(
            hiRx::racine_race_pop_weights_by_tract,
            hiRx::racine_race_pop_weights_by_tract %>%
                dplyr::group_by(
                    .data$Year, .data$Municipality, .data$tract
                ) %>%
                dplyr::summarize(
                    dplyr::across(tidyselect::ends_with("Population"), sum),
                    .groups = "keep"
                ) %>%
                dplyr::ungroup() %>%
                dplyr::mutate(`Race/Ethnicity` = "All")
        ),
        by = c(
            Vintage = "Year",
            "tract",
            "Race/Ethnicity"
        )
    ) %>%
    dplyr::group_by(
        .data$Year,
        .data$Municipality,
        .data$tract,
        .data$`Race/Ethnicity`
    ) %>%
    dplyr::summarize(
        People = sum(.data$`Municipal Population`),
        dplyr::across(
            tidyselect::starts_with("Income"),
            weighted.mean,
            w = .data$`Municipal Population` / .data$`Tract Population`
        ),
        .groups = "keep"
    ) %>%
    dplyr::group_by(
        .data$Year,
        .data$Municipality,
        .data$`Race/Ethnicity`
    ) %>%
    dplyr::summarize(
        Population = sum(.data$People),
        dplyr::across(
            tidyselect::starts_with("Income"),
            spatstat.geom::weighted.median,
            w = .data$People
        ),
        .groups = "keep"
    ) %>%
    dplyr::ungroup()
```

```{r income_by_race_and_place}

clean_up_income <- function(.x, ...) {
    .x %>%
        dplyr::filter(
            !is.na(.data$Municipality)
        ) %>%
        dplyr::group_by(
            .data$Municipality,
            .data$Year,
            ...
        ) %>%
        dplyr::summarize(
            `Median Income` = spatstat.geom::weighted.median(
                .data$Income,
                .data$`Municipal Population`
            ),
            `Adjusted Median Income` = spatstat.geom::weighted.median(
                .data$`Income in 2020 Dollars`,
                .data$`Municipal Population`
            ),
            `Sample Size` = sum(.data$`Municipal Population`),
            .groups = "keep"
        ) %>%
        dplyr::ungroup() %>%
        dplyr::mutate(
            Municipality = forcats::fct_reorder(.data$Municipality,
                                                .data$`Adjusted Median Income`,
                                                .fun = max)
        )
}

PLACE_INCOMES <- INCOME_BY_TRACT %>%
    dplyr::filter(
        .data$`Race/Ethnicity` == "Everybody"
    ) %>%
    dplyr::inner_join(
        hiRx::racine_race_pop_weights_by_tract %>%
            dplyr::group_by(.data$Year,
                            .data$Municipality,
                            .data$tract) %>%
            dplyr::summarize(`Municipal Population` = sum(.data$`Municipal Population`),
                             .groups = "keep"),
        by = c(Vintage = "Year", "tract")
    ) %>%
    clean_up_income()

PLACE_AND_RACE_INCOMES <- INCOME_BY_TRACT %>%
    dplyr::inner_join(
        dplyr::filter(hiRx::racine_race_pop_weights_by_tract,
                      .data$`Municipal Population` > 0),
        by = c(Vintage = "Year", "tract", "Race/Ethnicity")
    ) %>%
    dplyr::filter(
        !is.na(.data$Municipality)
    ) %>%
    clean_up_income(.data$`Race/Ethnicity`)
```

```{r plot_income_trends}
PLACE_AND_RACE_INCOMES %>%
    ggplot2::ggplot(
        ggplot2::aes(x = .data$Year,
                     y = .data$`Adjusted Median Income`,
                     fill = .data$`Race/Ethnicity`)
    ) +
    ggplot2::geom_col(position = "dodge") +
    ggplot2::scale_x_continuous(
        breaks = .ACS5_INCOME_YEARS,
        minor_breaks = NULL
    ) +
    ggplot2::scale_y_continuous(
        labels = scales::label_dollar(),
        limits = c(0, 150000)
    ) +
    hiRx::scale_fill_higher_ex("race", n.colors = 3) +
    ggplot2::facet_wrap(ggplot2::vars(.data$Municipality)) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.position = "right")
```

```{r compare_incomes_across_munis}
PLACE_INCOMES %>%
    ggplot2::ggplot(
        ggplot2::aes(x = .data$Year,
                     y = .data$`Adjusted Median Income`,
                     fill = .data$Municipality)
    ) +
    ggplot2::geom_col(position = "dodge") +
    ggplot2::scale_x_continuous(
        breaks = .ACS5_INCOME_YEARS,
        minor_breaks = NULL
    ) +
    ggplot2::scale_y_continuous(
        labels = scales::label_dollar()
    ) +
    ggplot2::scale_fill_viridis_d(option = "E", direction = -1) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.position = "right")
```

