---
title: "Median Household Incomes from the ACS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Median Household Incomes from the ACS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
content_size <- c(width = 7, height = 4)
content_dpi <- 96
knitr::opts_chunk$set(
    collapse = TRUE,
    warning = FALSE,
    message = FALSE,
    comment = "#>",
    cache = TRUE,
    dpi = content_dpi,
    fig.dim = content_size
)
```

```{r setup}
library(rlang)
library(magrittr)
library(hiRx)

tigershapes_combine <- function(file_names,
                                shapefile_path,
                                ...) {
    .filter_commands = rlang::enquos(...)
    file_names %>%
    purrr::imap(
        ~ file.path(shapefile_path,
                    .y,
                    .x) %>%
            sf::st_read() %>%
            dplyr::rename_with(
                stringr::str_remove,
                pattern = paste0(stringr::str_extract(.y,
                                                      "\\d{2}$"),
                                 "$")
            ) %>%
            dplyr::filter(
                !!!.filter_commands
            )    
    ) %>%
    dplyr::bind_rows(
        .id = "Year"
    ) %>%
    dplyr::mutate(
        Year = as.integer(.data$Year),
        dplyr::across(
            tidyselect::starts_with("INTPT"),
            as.numeric
        )
    )
}

tibble_from_json <- function(.l, .names_from = c("data", "labels")) {
    
    .option <- rlang::arg_match(.names_from)
    
    if (.option == "data") {
        .names <- as.character(.l[[1]])
        .l <- tail(.l, -1)
    }
    else if (.option == "labels") {
        .names <- names(.l[[1]])
    }
    .l %>%
        purrr::transpose(.) %>%
        tibble::as_tibble(.name_repair = ~ .names) %>%
        dplyr::mutate(dplyr::across(.fns = as.character))
}

```

```{r load_geographies}
DATA_PATH <- file.path(path.expand("~"),
                       "Higher Expectations/Data/Downloads")

SHAPEFILE_PATH <- file.path(DATA_PATH,
                            "Census Shapefiles")

PLACE_FILES <- c(
    `2000` = "tl_2010_55101_cousub00.shp",
    `2010` = "tl_2010_55101_cousub10.shp",
    `2020` = "tl_2020_55_cousub.shp"
)

PLACES <- tigershapes_combine(PLACE_FILES,
                              SHAPEFILE_PATH,
                              .data$COUNTYFP == "101") %>%
    dplyr::filter(
        .data$ALAND > 0,
        .data$INTPTLON < -87.7,
        .data$INTPTLON > -87.96
    )

BLOCK_GROUP_FILES <- c(
    `2000` = "tl_2010_55101_bg00.shp",
    `2010` = "tl_2010_55101_bg10.shp",
    `2020` = "tl_2020_55_bg.shp"
)

BLOCK_GROUPS <- tigershapes_combine(BLOCK_GROUP_FILES,
                                    SHAPEFILE_PATH,
                                    .data$COUNTYFP == "101") %>%
    dplyr::filter(
        .data$ALAND > 0,
        .data$INTPTLON < -87.7,
        .data$INTPTLON > -87.96
    )

BLOCK_FILES <- c(
    `2000` = "tl_2010_55101_tabblock00.shp",
    `2010` = "tl_2010_55101_tabblock10.shp",
    `2020` = "tl_2020_55_tabblock20.shp"
)

BLOCKS <- tigershapes_combine(BLOCK_FILES,
                              SHAPEFILE_PATH,
                              .data$COUNTYFP == "101") %>%
    dplyr::filter(
        .data$ALAND > 0,
        .data$INTPTLON < -87.7,
        .data$INTPTLON > -87.96
    )
```

```{r wrangle_geographies}
PLACE_BLOCKS <- sf::st_relate(PLACES,
                              BLOCKS,
                              pattern = "T********",
                              sparse = FALSE) &
    outer(PLACES$Year,
          BLOCKS$Year,
          "==")

# county_tracts <- county_blocks %>%
#     dplyr::group_by(
#         .data$TRACTCE
#         ) %>%
#     dplyr::summarize(
#         POP = sum(.data$POP),
#         Area = sum(.data$ALAND + .data$AWATER),
#         geometry = sf::st_union(.data$geometry)
#     ) %>%
#     dplyr::ungroup() %>%
#     dplyr::bind_cols(
#         .,
#         .$geometry %>%
#             sf::st_centroid() %>%
#             sf::st_coordinates()
#     )
# 
# racine_tracts <- county_tracts %>%
#     sf::st_filter(racine_city)
# 
# eastern_tracts <- county_tracts %>%
#     dplyr::filter(.data$X > -88,
#                   .data$X < -87.7
#     )

```

```{r census_details}
foo <- "acs5 2020 variables.json" %>%
    file.path(DATA_PATH, .) %>%
    jsonlite::read_json() %>%
    purrr::pluck(1)

census_details <- foo %>%
    purrr::transpose(.) %>%
    tibble::as_tibble() %>%
    dplyr::mutate(
        dplyr::across(.fns = as.character),
        variable = names(foo)
        ) %>%
    dplyr::filter(
        stringr::str_detect(.data$group,
                            "B")
        )
rm(foo)
```

```{r census_race_names}

.HEX_RACE_LABELS <- c(
    "Black",
    "Latin@",
    "White",
    "All Other Races",
    "Multiracial"
)

.HEX_HISP_LABELS <- c(
    "Latin@",
    "Not Latin@",
    "Unknown"
)

.RACE_MAP <- c(
    `NATIVE HAWAIIAN AND OTHER PACIFIC ISLANDER ALONE` = .HEX_RACE_LABELS[4],
    `ASIAN ALONE` = .HEX_RACE_LABELS[4],
    `HISPANIC OR LATINO` = .HEX_RACE_LABELS[2],
    `WHITE ALONE` = .HEX_RACE_LABELS[3],
    `SOME OTHER RACE ALONE` = .HEX_RACE_LABELS[4],
    `TWO OR MORE RACES` = .HEX_RACE_LABELS[5],
    `BLACK OR AFRICAN AMERICAN ALONE` = .HEX_RACE_LABELS[1],
    `AMERICAN INDIAN AND ALASKA NATIVE ALONE` = .HEX_RACE_LABELS[4],
    `WHITE ALONE, NOT HISPANIC OR LATINO` = .HEX_RACE_LABELS[3]
)

.HISP_MAP <- c(
    `NATIVE HAWAIIAN AND OTHER PACIFIC ISLANDER ALONE` = .HEX_HISP_LABELS[2],
    `ASIAN ALONE` = .HEX_HISP_LABELS[2],
    `HISPANIC OR LATINO` = .HEX_HISP_LABELS[1],
    `WHITE ALONE` = .HEX_HISP_LABELS[3],
    `SOME OTHER RACE ALONE` = .HEX_HISP_LABELS[3],
    `TWO OR MORE RACES` = .HEX_HISP_LABELS[3],
    `BLACK OR AFRICAN AMERICAN ALONE` = .HEX_HISP_LABELS[3],
    `AMERICAN INDIAN AND ALASKA NATIVE ALONE` = .HEX_HISP_LABELS[3],
    `WHITE ALONE, NOT HISPANIC OR LATINO` = .HEX_RACE_LABELS[3],
    `Hispanic or Latino` = .HEX_HISP_LABELS[1],
    `NA` = .HEX_HISP_LABELS[3],
    `Not Hispanic or Latino` = .HEX_HISP_LABELS[2]
)
```

```{r household_variables}
household_variables <- census_details %>%
    dplyr::filter(
        stringr::str_detect(.data$group,
                            "^B11001"),
        stringr::str_detect(.data$variable,
                            "_001")
    ) %>%
    tidyr::separate(
        col = .data$label,
        into = c(NA, NA, "Census Latin@ Status", "Census Race"),
        sep = "!!",
        fill = "right",
        extra = "drop",
        remove = FALSE
    ) %>%
    dplyr::mutate(
        dplyr::across(c(.data$`Census Latin@ Status`,
                        .data$`Census Race`),
                      stringr::str_remove_all,
                      pattern = ":"),
        `Race Ethnicity` = .RACE_MAP[stringr::str_to_upper(.data$`Census Race`)],
        `Latin@ Status` = .HISP_MAP[.data$`Census Latin@ Status`]
    ) %>%
    dplyr::select(
        .data$variable,
        .data$`Census Latin@ Status`,
        .data$`Census Race`,
        .data$`Latin@ Status`,
        .data$`Race Ethnicity`
    )
```

```{r income_variables}
income_variables <- census_details %>%
    dplyr::filter(
        stringr::str_detect(.data$group,
                            "B19013"),
        stringr::str_detect(.data$concept,
                            "^MEDIAN")
        ) %>%
    dplyr::mutate(
        `Census Race` = .data$concept %>%
            stringr::str_remove(
                string = .,
                pattern = "MEDIAN HOUSEHOLD INCOME IN THE PAST 12 MONTHS \\(IN \\d{4} INFLATION-ADJUSTED DOLLARS\\)"
            ) %>%
            stringr::str_remove_all(
                string = .,
                pattern = "\\(|\\)|HOUSEHOLDER"
            ) %>%
            stringr::str_squish(.),
        `Latin@ Status` = .RACE_MAP[.data$`Census Race`],
        `Race Ethnicity` = .RACE_MAP[.data$`Census Race`]
    ) %>%
    dplyr::select(
        .data$variable,
        .data$`Census Race`,
        .data$`Race Ethnicity`,
        .data$`Latin@ Status`
    )
```


```{r health_by_tract}
health_by_tract <- acs5_query_url(2020,
                health_variables$variable,
                "tract",
                racine_tracts$TRACTCE,
                state = 55,
                county = 101) %>%
    jsonlite::read_json() %>%
    tibble_from_json() %>%
    tidyr::pivot_longer(
        cols = !c(.data$state, .data$county, .data$tract),
        names_to = "variable",
        values_to = "people",
        values_transform = list(people = as.integer)
    ) %>%
    dplyr::rename(TRACTCE = .data$tract) %>%
    dplyr::left_join(health_variables, by = "variable")

age_totals <- health_by_tract %>%
    dplyr::group_by(
        .data$Age,
                    .data$TRACTCE
        ) %>%
    dplyr::summarize(
        `Age Total` = sum(.data$people)
        )

health_by_tract <- health_by_tract %>%
    dplyr::filter(
        .data$Covered == "Yes"
        ) %>%
    dplyr::select(
        .data$TRACTCE,
        .data$Age,
        .data$people
        ) %>%
    dplyr::left_join(
        age_totals,
                     by = c("Age", "TRACTCE")
        ) %>%
    dplyr::rename(
        `People Covered` = .data$people,
        `Total People` = .data$`Age Total`
        ) %>%
    dplyr::mutate(
        Age = factor(.data$Age,
                     levels = unique(.data$Age)),
        Coverage = .data$`People Covered` / .data$`Total People`
        )
```

```{r plot_health_and_age, fig.dim = c(8, 3.2), out.width = "90%", fig.align = "center"}
racine_tracts %>%
    dplyr::left_join(health_by_tract, by = "TRACTCE") %>%
    ggplot2::ggplot() +
    ggplot2::geom_sf(ggplot2::aes(fill = .data$Coverage)) +
    ggplot2::geom_sf(data = racine_city,
                     color = "yellow",
                     fill = NA) +
    ggplot2::theme_minimal() +
    ggplot2::facet_grid(cols = ggplot2::vars(.data$Age)) +
    ggplot2::scale_fill_continuous(labels = scales::label_percent(1)) +
    ggplot2::scale_x_continuous(breaks = seq(-87.85, -87.6, by = 0.05)) +
    ggplot2::scale_y_continuous(breaks = seq(42.65, 42.85, by = 0.05))
```
